apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: victorcuches28/server_grpc_client
        imagePullPolicy: Always
        name: client
        ports:
          - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 7000
      targetPort: 7000
  selector:
    app: client
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - image: victorcuches28/server_grpc_server
        imagePullPolicy: Always
        name: grpc-server
        ports:
          - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 7001
      targetPort: 7001
  selector:
    app: grpc-server