apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyecto-ingress
  namespace: so1p2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: proyectovc.com
    http:
      paths:
      - path: /grpc
        pathType: Prefix
        backend:
          service:
            name: grpc-client
            port:
              number: 7000
      - path: /py_node
        pathType: Prefix
        backend:
          service:
            name: api-python
            port:
              number: 5000
      