apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-node
  name: api-node
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-node
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
      - image: victorcuches28/server_node
        imagePullPolicy: Always
        name: api-node
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-node
  name: api-node
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 5000
      targetPort: 5000
  selector:
    app: api-node