apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: so1p2
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app: redis