apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-python
  name: api-python
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-python
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: api-python
    spec:
      containers:
      - image: gcr.io/swift-synthesis-397705/server_python
        imagePullPolicy: Always
        name: api-python
        ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-python
  name: api-python
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 4000
      targetPort: 4000
  selector:
    app: api-python